global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'heroin-server'
    static_configs:
      - targets: ['heroin-server:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
