server:
  listen:
    tcp: ":8080"
    quic: ":8443"
  tls:
    cert_file: ""
    key_file: ""
  transports:
    enable_tcp: true
    enable_quic: true
    enable_ws: true
    enable_wss: true
routing:
  strategy: "adaptive"
  bootstrap_nodes:
    - "/dns4/bootstrap.heroin.dev/tcp/443/wss/p2p/12D3KooExample"
  relays:
    - "/dns4/relay.heroin.dev/tcp/443/wss/p2p/12D3KooExample"
  switch_threshold_ms: 500
  metrics_window_sec: 120
ipfs:
  endpoint: "http://127.0.0.1:5001"
  pinning_enabled: true
  replication_factor: 3
security:
  kdf:
    type: "argon2id"
    time: 3
    memory_mb: 64
    threads: 2
    key_len: 32
  token:
    issuer: "heroin"
    lifetime_min: 30
    refresh_days: 30
  secondary_key:
    length: 10
    rotate_minutes: 30
    allowed_clock_skew_sec: 120
  tls_fingerprint: "chrome_auto"
database:
  dsn: "file:heroin.db?_pragma=journal_mode(WAL)&_pragma=foreign_keys(ON)"
logging:
  level: "info"
observability:
  prometheus_addr: ":9090"
  otlp_endpoint: ""
