server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 15  # секунды
  write_timeout: 15 # секунды

database:
  host: "localhost"
  port: "5432"
  user: "hero_user"
  password: "hero_pass"
  name: "hero_n"
  ssl_mode: "disable"

p2p:
  port: "4001"
  discovery_enabled: true
  rendezvous_point: "/hero-n/1.0.0"
  # bootstrap_peers: []  # для продакшена добавить реальные адреса

crypto:
  key_size: 32
  hash_algorithm: "sha256"

logging:
  level: "info"
  format: "text"

# Development settings
debug: true
node_type: "bootstrap"
